name: EAS Build

on:
  push:
    branches: [main]
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  build:
    name: Build on EAS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      
      - uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      
      - run: npx eas-cli build --platform all --profile production --non-interactive --no-wait
